name: CI for Pull requests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
      - name: Lint
        run: npm run lint
      - name: Type
        run: npm run type
